version: '3'
services:
  go:
    container_name: 'go_docker'
    image: 'golang:1.9.2-stretch'
    working_dir: '/go/src'
    volumes:
      - 'data:/go'
      - './go_app:/go/src'
    ports:
      - '3010:8080'
    command: 'go run main.go'
volumes:
  data:
    driver: 'local'